services:
  # 1. User 도메인 DB
  user-db:
    image: mysql:8.0
    container_name: user_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: user12
      MYSQL_DATABASE: user_db
      TZ: Asia/Seoul
    ports:
      - "3310:3306"
    volumes:
      - ./user_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # 2. Order 도메인 DB
  order-db:
    image: mysql:8.0
    container_name: order_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: order12
      MYSQL_DATABASE: order_db
      TZ: Asia/Seoul
    ports:
      - "3311:3306"
    volumes:
      - ./order_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # 3. Catalog 도메인 DB
  catalog-db:
    image: mysql:8.0
    container_name: catalog_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: catalog12
      MYSQL_DATABASE: catalog_db
      TZ: Asia/Seoul
    ports:
      - "3312:3306"
    volumes:
      - ./catalog_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M