spring:
  config:
    import:
      - "../common/eureka-client.yml"
      - "../common/actuator.yml"
      - "../common/jpa.yml"
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3311/order_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: order12
    driver-class-name: com.mysql.cj.jdbc.Driver