spring:
  config:
    import:
      - "../common/actuator.yml"
      - "../common/cloud-bus.yml"
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    response-cache-update-interval-ms: 500
    eviction-interval-timer-in-ms: 3000