server:
  port: 0

grpc:
  client:
    orderService:
      address: 'discovery:///ORDER-SERVICE'
      negotiation-type: plaintext
      default-load-balancing-policy: round_robin

spring:
  application:
    name: user-service
  config:
    import: "configserver:http://localhost:8888"

logging:
  level:
    com.example.user_service.client: DEBUG