server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ajroot5685/microservice.git
          default-label: main
          search-paths:
            - config-files/common
            - config-files/services
          clone-on-start: true
          force-pull: true
    stream:
      bindings:
        springCloudBusInput:
          group: ${spring.application.name}-bus-group

management:
  endpoints:
    web:
      exposure:
        include: "health,busrefresh"
  endpoint:
    health:
      show-details: always